### ISSUE TITLE
Logger creation error

### ISSUE THREAD

**Issue by wildart** [cocaine/cocaine-framework-nodejs#10]
I'm trying to create logger by running following code (node 0.10.17) 

```
var co = require('cocaine')
var Logger = co.Service('logging')
L = new Logger(argv.app)
L.info("test")
```

it generates an error:

```
/home/test/test/node_modules/cocaine/lib/services/logging.js:32
    this.verbosity()
         ^
TypeError: Object #<EventEmitter> has no method 'verbosity'
    at EventEmitter.Logger [as __cls] (/home/art/Development/flood-bridge/node_modules/cocaine/lib/services/logging.js:32:10)
    at Object.<anonymous> (/home/art/Development/flood-bridge/bridge.js:21:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain [as _onTimeout] (module.js:497:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by green13** [comment]
Hi, I have a problem with logger.
I'm trying to add logger to my app (worker):

```
var cocaine = require('cocaine');
var cli = new cocaine.Client(); // ["localhost", 10053]
var L = new cli.Logger("farkleportal") 

L.connect(); // error
```


Error:

```
/var/spool/cocaine/farkleportal/node_modules/cocaine/lib/client/service.js:152
    (_this._client || client).resolve(_this._name, _resolveDone)
                              ^
TypeError: Object [object Object] has no method 'resolve'
    at _resolve (/var/spool/cocaine/farkleportal/node_modules/cocaine/lib/client/service.js:152:31)
    at EventEmitter.serviceConnect [as connect] (/var/spool/cocaine/farkleportal/node_modules/cocaine/lib/client/service.js:142:5)
    at EventEmitter.Logger.connect (/var/spool/cocaine/farkleportal/node_modules/cocaine/lib/client/logger.js:50:21)
    at Object.<anonymous> (/var/spool/cocaine/farkleportal/utils/logger.js:8:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```


Cocaine module version: "0.4.1-6".

**Comment by diunko** [comment]
That's an inaccuracy in readme, since cli.Logger is a factory function, not a constructor. So, you can create logger like this:

```
var cocaine = require('cocaine');
var cli = new cocaine.Client(); // ["localhost", 10053]
var L = cli.Logger("farkleportal") 

L.connect(); 
```

See also https://github.com/cocaine/cocaine-framework-nodejs/blob/v0.4/sample/client.0.js or https://github.com/cocaine/cocaine-framework-nodejs/blob/v0.4/sample/client.1.js
